package es.mappatura.northwind;

import java.math.BigDecimal;

/**
 * OrderDetails generated by hbm2java
 */
public class OrderDetails implements java.io.Serializable {

	private OrderDetailsId id;
	private BigDecimal unitPrice;
	private Short quantity;
	private Double discount;

	public OrderDetails() {
	}

	public OrderDetails(OrderDetailsId id) {
		this.id = id;
	}

	public OrderDetails(OrderDetailsId id, BigDecimal unitPrice,
			Short quantity, Double discount) {
		this.id = id;
		this.unitPrice = unitPrice;
		this.quantity = quantity;
		this.discount = discount;
	}

	public OrderDetailsId getId() {
		return this.id;
	}

	public void setId(OrderDetailsId id) {
		this.id = id;
	}

	public BigDecimal getUnitPrice() {
		return this.unitPrice;
	}

	public void setUnitPrice(BigDecimal unitPrice) {
		this.unitPrice = unitPrice;
	}

	public Short getQuantity() {
		return this.quantity;
	}

	public void setQuantity(Short quantity) {
		this.quantity = quantity;
	}

	public Double getDiscount() {
		return this.discount;
	}

	public void setDiscount(Double discount) {
		this.discount = discount;
	}

}
